#pragma once
#include <string>
#include <vector>
#include <list>
#include <map>
#include <assert.h>
#include <Windows.h>
#include <stdlib.h>
#include <malloc.h>
#include <memory.h>
#include <tchar.h>
